Repository ifLabX/AgentifUI, pull requests merged in 2025-08, with the labels that each got.

#183 docs: cleanup unused files and fix pm2 scripts
  docs/FONTS.md
  docs/README-API-KEY-MANAGEMENT.md
  docs/dynamic-translation-system.md
  docs/password-reset-comprehensive-guide.md
  docs/password-reset-guide.md
  docs/supabase-docs.md
  ecosystem.config.js
Labels: type:docs, lgtm, size:XXL

#185 fix(security): patch profile cache vulnerabilities
  .github/workflows/bundle-analysis.yml
  .github/workflows/ci.yml
  .github/workflows/claude.yml
  .husky/pre-commit
  __tests__/utils/profile-cache-security.test.ts
  lib/hooks/use-profile.ts
  lib/utils/profile-cache-security.ts
  package.json
Labels: type:security, lgtm, size:XXL

#187 docs: restructure and clean up docs, clarify i18n and testing workflow
  .cursor/rules/cursor-rules.mdc
  .cursor/rules/i18n.mdc
  .cursor/rules/test.mdc
  .github/ISSUE_TEMPLATE/03-documentation.yml
  CLAUDE.md
  README.md
  docs/DEPLOYMENT-GUIDE.md
  docs/DEVELOPMENT-TOOLS.md
  docs/QUICK-DEPLOYMENT.md
  docs/SETUP-REQUIREMENTS.md
  lib/utils.ts
Labels: type:docs, lgtm, size:XXL

#191 refactor(agents): align Claude agents with AgentifUI project requirements
  .claude/agents/ci-code-reviewer.md
  .claude/agents/code-linter-formatter.md
  .claude/agents/issue-driven-tester.md
  .claude/agents/project-maintainer.md
Labels: type:refactor, lgtm, area:agent, size:L

#192 feat(admin): add search functionality to application instances list
  app/admin/api-config/layout.tsx
  components/history/index.tsx
  components/ui/index.ts
  components/ui/search-input.tsx
  messages/de-DE.json
  messages/en-US.json
  messages/es-ES.json
  messages/fr-FR.json
  messages/it-IT.json
  messages/ja-JP.json
  messages/pt-PT.json
  messages/ru-RU.json
  messages/zh-CN.json
  messages/zh-TW.json
Labels: type:feature, lgtm, area:ui, size:L

#194 feat(file-preview): implement comprehensive document preview system with i18n support
  .gitignore
  CLAUDE.md
  app/api/dify/[appId]/[...slug]/route.test.ts
  app/api/dify/[appId]/[...slug]/route.ts
  components/admin/api-config/provider-management-modal.tsx
  components/chat-input/attachment-preview-item.spec.tsx
  components/chat-input/attachment-preview-item.tsx
  components/chat-input/chat-input.tsx
  components/chat-input/index.tsx
  components/chat-input/model-selector-button.tsx
  components/chat/messages/user-message/file-attachment-display.tsx
  components/chat/messages/user-message/user-message.tsx
  components/file-preview/file-preview-canvas.tsx
  components/file-preview/previews/audio-preview.tsx
  components/file-preview/previews/image-preview.tsx
  components/file-preview/previews/markdown-preview.tsx
  components/file-preview/previews/pdf-preview.tsx
  components/file-preview/previews/text-preview.tsx
  components/file-preview/previews/video-preview.tsx
  components/workflow/workflow-input-form/file-upload-field.tsx
  lib/api/dify/handlers/media-response-handler.test.ts
  lib/api/dify/handlers/media-response-handler.ts
  lib/hooks/use-chatflow-state.ts
  lib/hooks/use-file-types-from-config.ts
  lib/services/dify/file-service.ts
  lib/services/dify/index.ts
  lib/services/dify/types.ts
  lib/stores/attachment-store.ts
  lib/stores/chat-store.ts
  lib/stores/ui/file-preview-cache-store.test.ts
  lib/stores/ui/file-preview-cache-store.ts
  lib/stores/ui/file-preview-store.ts
  lib/utils/cache-cleanup.ts
  lib/utils/sse-parser.ts
  messages/de-DE.json
  messages/en-US.json
  messages/es-ES.json
  messages/fr-FR.json
  messages/it-IT.json
  messages/ja-JP.json
  messages/pt-PT.json
  messages/ru-RU.json
  messages/zh-CN.json
  messages/zh-TW.json
  middleware.ts
  package.json
  tailwind.config.js
Labels: type:feature, lgtm, area:ui, size:XXL

#198 fix(sidebar): ensure consistent highlight mutex behavior across all navigation buttons
  __tests__/components/sidebar/sidebar-highlight-mutex.test.ts
  components/sidebar/sidebar-footer.tsx
  components/sidebar/sidebar-header.tsx
Labels: type:bug, lgtm, area:ui, size:L

#200 fix: clean up lint issues with safe unused variable and import removal
  app/apps/chatflow/[instanceId]/page.tsx
  app/chat/[conversationId]/page.tsx
  components/chatflow/chatflow-execution-bar.tsx
  components/chatflow/chatflow-floating-controller.tsx
  components/ui/dropdown-menu.tsx
  components/ui/message-actions-container.tsx
  components/ui/tooltip-wrapper.tsx
  components/workflow/execution-history/index.tsx
  components/workflow/workflow-layout.tsx
  eslint.config.mjs
  i18n/request.ts
  lib/hooks/use-api-config.ts
  lib/hooks/use-chat-interface.ts
  lib/hooks/use-chat-page-state.ts
  lib/hooks/use-chatflow-interface.ts
  lib/hooks/use-sidebar-conversations.ts
Labels: type:refactor, lgtm, area:ui, size:L

#204 feat(ci): optimize CI workflows and i18n translation system
  .github/workflows/auto-i18n-translation.yml
  .github/workflows/ci.yml
  .gitignore
  app/admin/api-config/layout.tsx
  app/admin/users/page.tsx
  components/admin/api-config/provider-management-modal.tsx
  components/admin/groups/group-members-modal.tsx
  components/admin/groups/groups-list.tsx
  components/admin/users/user-table.tsx
  eslint.config.mjs
  messages/en-US.json
  messages/zh-CN.json
  package.json
  scripts/auto-gen-i18n.js
  scripts/i18n-refactor-helper.py
Labels: type:feature, type:refactor, lgtm, size:XXL

#206 fix(ci): replace GITHUB_TOKEN with GH_PAT for PR creation
  .github/workflows/auto-i18n-translation.yml
Labels: type:bug, size:XS

#207 fix(i18n): replace hardcoded text with translation in file preview
  components/file-preview/file-preview-canvas.tsx
  messages/en-US.json
  messages/zh-CN.json
Labels: type:bug, area:ui, size:XS

#210 feat: add ccusage statusline
  .claude/settings.json
Labels: type:feature, lgtm, size:XS

#212 chore: lock pnpm version to 10.14.0
  .github/workflows/auto-i18n-translation.yml
  .github/workflows/autofix.yml
  .github/workflows/ci.yml
  .github/workflows/security.yml
  package.json
Labels: type:refactor, lgtm, size:S

#216 refactor(ui): convert desktop-user-avatar to Tailwind best practices
  components/nav-bar/desktop-user-avatar.tsx
Labels: type:refactor, lgtm, area:ui, size:M

#217 fix(provider): improve provider management modal UI and functionality
  app/admin/api-config/page.tsx
  components/admin/api-config/provider-management-modal.tsx
  components/admin/api-config/provider-management/index.ts
  components/admin/api-config/provider-management/provider-card.tsx
  components/admin/api-config/provider-management/provider-form.tsx
  components/admin/api-config/provider-management/provider-management-modal.tsx
  components/ui/button.tsx
  components/ui/close-button.tsx
  components/ui/confirm-dialog.tsx
  components/ui/input.tsx
  components/ui/select.tsx
  components/ui/switch.tsx
  messages/en-US.json
Labels: type:bug, type:feature, type:refactor, lgtm, area:ui, size:XXL

#219 chore: update favicon.ico
  app/favicon.ico
Labels: lgtm, area:ui, size:XS

#230 refactor: replace isDark conditional logic with Tailwind dark: prefix across remaining components
  app/admin/page.tsx
  components/auth/social-auth-buttons.tsx
  components/chat-input/button.tsx
  components/chat-input/container.tsx
  components/chat-input/file-type-selector.tsx
  components/chat-input/index.tsx
  components/mobile/mobile-nav-button.tsx
  components/mobile/ui/bottom-sheet.tsx
  components/sidebar/sidebar-chat-icon.tsx
  components/sidebar/sidebar-container.tsx
  components/sidebar/sidebar-header.tsx
  components/ui/adaptive-key-badge.tsx
  components/ui/dropdown.tsx
  components/ui/message-action-button.tsx
  components/ui/more-button-v2.tsx
Labels: type:refactor, lgtm, area:ui, size:L

#232 refactor: migrate isDark conditionals to Tailwind CSS dark prefix across workflow components
  components/text-generation/text-generation-layout.tsx
  components/text-generation/text-generation-result-viewer.tsx
  components/workflow/history-button.tsx
  components/workflow/mobile-tab-switcher.tsx
  components/workflow/workflow-input-form/index.tsx
  components/workflow/workflow-layout.tsx
  components/workflow/workflow-tracker/index.tsx
Labels: type:refactor, lgtm, area:ui, size:L

#233 fix(ui): correct color mapping in sidebar and chat-input components
  components/chat-input/button.tsx
  components/chat-input/container.tsx
  components/sidebar/sidebar-container.tsx
Labels: type:bug, lgtm, area:ui, size:S

#241 chore: Delete .claude/agents directory
  .claude/agents/ci-code-reviewer.md
  .claude/agents/code-linter-formatter.md
  .claude/agents/issue-driven-tester.md
  .claude/agents/project-maintainer.md
Labels: lgtm, area:agent, size:L
