Repository ifLabX/AgentifUI, pull requests merged in 2025-07, with the labels that each got.

#169 fix(ui): fix text overflow in markdown block headers
  components/chat/markdown-block/code-block-header.spec.tsx
  components/chat/markdown-block/code-block-header.tsx
  components/chat/markdown-block/think-block-header.spec.tsx
  components/chat/markdown-block/think-block-header.tsx
  jest.config.js
  jest.setup.js
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: type:bug, area:ui, size/XL

#170 chore(test): lower coverage threshold and ignore config files
  jest.config.js
Labels: lgtm, size:S

#173 fix(workflow): replace unsupported pnpm update options with ncu for patch/minor/major updates
  .github/workflows/dependency-update.yml
Labels: type:deps, lgtm, area:agent, size:M

#176 feat: optimize development and deployment workflow
  .github/workflows/autofix.yml
  .github/workflows/bundle-analysis.yml
  ecosystem.config.js
  lib/hooks/use-chat-interface.ts
  middleware.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
Labels: type:feature, lgtm, size:L

#177 docs: simplify PR template and contributing guide
  .github/CLA.md
  .github/CODE_OF_CONDUCT.md
  .github/NOTICE
  .github/PULL_REQUEST_TEMPLATE.md
  .github/TRADEMARK_POLICY.md
  CONTRIBUTING.md
Labels: type:docs, lgtm, size:L

#180 docs: update the deployment guide
  docs/DATABASE-DESIGN.md
  docs/DEPLOYMENT-GUIDE.md
  docs/DEVELOPMENT-TOOLS.md
Labels: type:docs, lgtm, size:XXL
