Repository ifLabX/AgentifUI, pull requests merged in 2025-09, with the labels that each got.

#246 fix(i18n): fix Start Exploring button navigation URL in all languages
  messages/de-DE.json
  messages/en-US.json
  messages/es-ES.json
  messages/fr-FR.json
  messages/it-IT.json
  messages/ja-JP.json
  messages/pt-PT.json
  messages/ru-RU.json
  messages/zh-CN.json
  messages/zh-TW.json
Labels: type:bug, lgtm, area:ui, size:S

#259 fix(ui): prevent confirm dialog from blocking background modal intera…
  components/ui/confirm-dialog.tsx
Labels: type:bug, lgtm, area:ui, size:S

#260 fix(settings): remove invalid Beijing timezone and fix validation feedback
  .gitignore
  app/settings/appearance/page.tsx
  components/settings/appearance/timezone-selector.tsx
  messages/de-DE.json
  messages/en-US.json
  messages/es-ES.json
  messages/fr-FR.json
  messages/it-IT.json
  messages/ja-JP.json
  messages/pt-PT.json
  messages/ru-RU.json
  messages/zh-CN.json
  messages/zh-TW.json
Labels: type:bug, lgtm, size:M

#274 feat(sso): add configurable email domain for SSO providers
  .env.example
  app/api/sso/[providerId]/callback/route.ts
  components/admin/sso-providers/sso-provider-form.tsx
  lib/services/admin/user/sso-user-service.ts
  lib/services/sso/generic-cas-service.ts
  messages/de-DE.json
  messages/en-US.json
  messages/es-ES.json
  messages/fr-FR.json
  messages/it-IT.json
  messages/ja-JP.json
  messages/pt-PT.json
  messages/ru-RU.json
  messages/zh-CN.json
  messages/zh-TW.json
Labels: type:feature, lgtm, area:ui, size:L
